### ISSUE TITLE
REPORTS: Add fail-safe error handling the Institutions report for when there is no data to display

### ISSUE THREAD

**Issue by bechandcock** [The-Academic-Observatory/observatory-platform#117]
In the Institutions report, when there is no data to display this gives these palette errors. @cameronneylon  suggested that it was in the Charting library. We need to add some error handling so that it fails safe when there is no data return from the query.

**Example**:
```
Running report for grid.7107.1: University of Aberdeen
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    render_file(j, analytics_modules, storages=storages)
  File "/Users/bec/GITHUB_WORK/precipy/precipy/main.py", line 19, in render_file
    custom_render_fns=custom_render_fns)
  File "/Users/bec/GITHUB_WORK/precipy/precipy/main.py", line 55, in render_data
    batch.run(analytics_modules)
  File "/Users/bec/GITHUB_WORK/precipy/precipy/batch.py", line 131, in run
    self.generate_analytics(analytics_modules)
  File "/Users/bec/GITHUB_WORK/precipy/precipy/batch.py", line 174, in generate_analytics
    h = self.process_analytics_entry(key, kwargs, previous_functions)
  File "/Users/bec/GITHUB_WORK/precipy/precipy/batch.py", line 195, in process_analytics_entry
    af.run_function()
  File "/Users/bec/GITHUB_WORK/precipy/precipy/analytics_function.py", line 86, in run_function
    self.function_output = self.call_function()
  File "/Users/bec/GITHUB_WORK/precipy/precipy/analytics_function.py", line 82, in call_function
    return self.fn(self, **kwargs)
  File "/Users/bec/GITHUB_WORK/coki-reports/reports/institution_report.py", line 419, in plot_graphs
    global_comparison_chart = global_comparison.plot()
  File "/Users/bec/GITHUB_WORK/coki-reports/reports/modules/layouts.py", line 128, in plot
    colorpalette=colorpalette)
  File "/Users/bec/GITHUB_WORK/academic-observatory/academic_observatory/analysis/charts/charts.py", line 260, in plot
    **scatterplot_kwargs)
  File "/Users/bec/opt/anaconda3/lib/python3.7/site-packages/seaborn/relational.py", line 1397, in scatterplot
    alpha=alpha, x_jitter=x_jitter, y_jitter=y_jitter, legend=legend,
  File "/Users/bec/opt/anaconda3/lib/python3.7/site-packages/seaborn/relational.py", line 893, in __init__
    self.parse_hue(plot_data["hue"], palette, hue_order, hue_norm)
  File "/Users/bec/opt/anaconda3/lib/python3.7/site-packages/seaborn/relational.py", line 373, in parse_hue
    list(data), order, palette
  File "/Users/bec/opt/anaconda3/lib/python3.7/site-packages/seaborn/relational.py", line 216, in categorical_to_palette
    raise ValueError(err)
ValueError: The palette list has the wrong number of colors.
```

**Comment by bechandcock** [comment]
Closing this issue as I think it has been addressed by the recent re-design of that code.

**Comment by cameronneylon** [comment]
This specific issue is resolved but there are a range of issues like this that need to be worked through to provide a robust self service approach. Will transfer error-handling into that project.
