### ISSUE TITLE
Automated Gmail API authentication

### ISSUE THREAD

**Issue by aroelo** [The-Academic-Observatory/observatory-platform#426]
A recent error occurred in @jdddog's environment stating that the token used for the Gmail API is invalid
See traceback:  
<details>

```
[2021-06-01 01:51:47,195] {taskinstance.py:1150} ERROR - ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 158, in execute
    condition = super(ShortCircuitOperator, self).execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/observatory-dags/observatory/dags/telescopes/jstor.py", line 271, in list_reports
    label_id = get_label_id(service, self.PROCESSED_LABEL_NAME)
  File "/opt/observatory-dags/observatory/dags/telescopes/jstor.py", line 496, in get_label_id
    existing_labels = service.users().labels().list(userId="me").execute()["labels"]
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/http.py", line 914, in execute
    headers=self.headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/http.py", line 176, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google_auth_httplib2.py", line 190, in request
    self._request, method, uri, request_headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
```
</details>

From the documentation (https://developers.google.com/identity/protocols/oauth2#expiration) I found that the token will expire after 7 days in our current set-up:  
> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

Possible solutions:
- Don't use an external user. This means that it needs to be a G-suite account. The downsides are that an extra G-suite account costs money and publishers are set-up to mail reports to the existing Gmail account.  
If we do use a G-suite account, the added benefit would be that we could grant domain-wide authority to our existing airflow service account and then use this for authentication of the Gmail API, making the actual authentication in the telescope easier. (https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority).
- Use something like Selenium to create new refresh tokens whenever they expire. I'm not sure if this would trigger a reCAPTCHA? I haven't tried it yet.
- Set the publishing status of our project to 'In production'. This is not an actual option, because as it turns out we need a 'restricted scope' for the gmail API (gmail.modify and gmail.readonly). This requires an expensive security assessment from Google. See https://support.google.com/cloud/answer/9110914
> Currently, assessments are conducted by a Google-designated third-party assessor, may cost between $15,000 and $75,000 (or more) depending on the complexity of the application, and is payable by the developer.

**Comment by jdddog** [comment]
> * Don't use an external user. This means that it needs to be a G-suite account. The downsides are that an extra G-suite account costs money and publishers are set-up to mail reports to the existing Gmail account.
>   If we do use a G-suite account, the added benefit would be that we could grant domain-wide authority to our existing airflow service account and then use this for authentication of the Gmail API, making the actual authentication in the telescope easier. (https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority).

This seems like the best solution. Could we update the existing Gmail account to a G-suite account, so that we don't need to change the email address?

**Comment by aroelo** [comment]
> > * Don't use an external user. This means that it needs to be a G-suite account. The downsides are that an extra G-suite account costs money and publishers are set-up to mail reports to the existing Gmail account.
> >   If we do use a G-suite account, the added benefit would be that we could grant domain-wide authority to our existing airflow service account and then use this for authentication of the Gmail API, making the actual authentication in the telescope easier. (https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority).
> 
> This seems like the best solution. Could we update the existing Gmail account to a G-suite account, so that we don't need to change the email address?

From what I'm reading it seems like you can't update the existing Gmail account directly, but you can migrate the old mail and forward any new incoming mails, so it would effectively be the same (https://support.google.com/a/answer/9216781).

**Comment by aroelo** [comment]
Gmail was added to the observatory G-suite account that we already had and the mails from the existing Gmail account are forwarded to this account.
